version: '3.8'

services:
  mongodb:
    image: mongo:5.0.5
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - db:$MONGODB_DB_PATH
  
  api:
    depends_on:
      - mongodb
    build: ./api
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - OWNER_PUBLIC_KEY=$OWNER_PUBLIC_KEY
    volumes:
      - files:$FILES_DIRECTORY

  nginx:
    depends_on:
      - api
    build: ./nginx
    restart: unless-stopped
    env_file: ./.env
    environment:
      - HASHNET_API_HOST=api:${NODE_DOCKER_PORT}
      - CLIENT_MAX_BODY_SIZE=$NGINX_MESSAGE_SIZE_LIMIT
    ports:
      - 80:80

#  ui:
#    depends_on:
#      - api
#    build:
#      context: ./ui

volumes: 
  db:
  files:
